### ISSUE TITLE
Can't resize dropdown label.

### ISSUE THREAD

**Issue by ghost** [RowellKataan/Unity-List-Box#1]
Hello, and first of all thanks for your nice job with this project!

I'm having difficulties to resize the main label of the dropdown. The internal labels, ones that show the dropdown items those can be resized perfectly. But when i resize the Label that shows the selected item nothing happens.

I have a vertical layout set to `child control size = true` and `child force expand = true`, if i set this to false, the background of the label dissapears.

My question is: Is it possible to make the dropdown consistent with the vertical layout functionality?

Thanks for your time, and feel free to ask whatever you need to improve this project.

Best regards.

**Comment by RowellKataan** [comment]
Hello Fernando,

I'll take a look at this today, and see what I can come up with as a solution.
Glad you like the project!

**Comment by RowellKataan** [comment]
I think I'm able to re-create the issue that you are experiencing.  To do so, I'm working with the Demo scene that came in the package.  I went into the "Demo DropDown Panel" object and re-ordered the objects within as such: DDL Result Text, Progress Bar, DropDown Prefab and finally Clear DDL Button.
I then created and empty object, named it "DDL Container", put the top left corner of the object to the top left corner of the DropDown Prefab object, then put the bottom right corner of the object to the bottom right corner of the Clear DDL Button object (making the rectangle pretty much contain the two objects.  I then added a Vertical Layout Group to the DDL Container object, clicked all the check boxes on (auto set width and height, and expand), and set the spacing to 10.  Then I moved the DropDown Prefab and the Clear DDL Button into the DDL Container Object.

When I execute the code, it runs as expected....mostly.  I can see the drop down list, select an item, and have it show up as selected.  The thing that I think you may be seeing trouble with is when you click on the drop down list.  In order for the control to work, I drop it in the list of children in its parent to the bottom of the list.  That way, if there are any controls visible, the drop down list will show up above it, so you can scroll and select an item.  (otherwise, the drop down list would show up behind buttons or text, ad you couldn't actually use it).  In my example, when I click on the drop down list, the order of controls changes (the button is first in the list, the drop down list is last).  The Vertical Layout Group is re-ordering the objects when the drop down list is clicked open, then resetting them when a selection is made (or you close the control).

I did find a problem with the drop down item container object not being properly resized.  I posted an update a short time ago.  I don't know if this addresses your specific problem (it might, I hope).  Give it a try and let me know if that resolves your issue.   If it does not, we can discuss in more detail what the symptoms of the problem are.

**Comment by ghost** [comment]
Thanks for your fast response,

The issue is not related to when the dropdown is open. The only problem is that in the default state(closed), the text inside the dropdown is higher than the background itself. On top of that, the vertical layout that the container of the dropdown has consider the background height and not the text height.

I guess the issue is related with the "best fit" check of the dropdown label wich im setting to true [10 - 40]

Anyway, i'm going to change my project canvas scaler, and remove the vertical layouts to place all manually, so you can close the issue if you want.

Thanks for your time.

**Comment by RowellKataan** [comment]
Ah, okay.  

I did notice in the example I posted above that the text in the button did get smaller, and was moved to the top of the button (not the center, even though I told the text to be centered).  Vertical Layout Group can do some unexpected things with formatting, from my past experience.

Thanks for reporting this.  If anything, an unfound bug was found and fixed. So there is some win here.  :)
